package io.example.therapy.therapy.entity;

import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;

import io.example.therapy.therapy.converter.EmotionListConverter;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "journal")
public class Journal {

    @DynamoDBHashKey(attributeName="journalId")
    @DynamoDBAutoGeneratedKey
    private String journalId; // Changed to String for DynamoDB compatibility

    @DynamoDBAttribute(attributeName="clientEmail")
    @DynamoDBIndexHashKey(globalSecondaryIndexName="ClientEmailIndex")
    @NotNull
    @Email
    private String clientEmail; // Renamed for clarity

    @DynamoDBAttribute(attributeName = "title")
    @NotNull
    @Size(max = 100) // Optional title length validation
    @DynamoDBIndexHashKey(globalSecondaryIndexName="TitleIndex")
    private String title;

    @DynamoDBAttribute(attributeName = "content")
    private String content;

    @DynamoDBAttribute(attributeName = "emotions")
    @DynamoDBTypeConverted(converter = EmotionListConverter.class) // Custom converter
    private List<Emotion> emotions = new ArrayList<>(); // Consider storing as JSON string if necessary

    @DynamoDBAttribute(attributeName = "therapists")
    private List<String> therapists=new ArrayList<>();
}
