/*
 * OpenAPI-for-emotional-journal
 *
 * Developing API for emotional journal app for assessment
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class IdNotesBody : IEquatable<IdNotesBody>
    { 
        /// <summary>
        /// Gets or Sets ClientId
        /// </summary>
        [Required]

        [DataMember(Name="clientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// Gets or Sets PrivateNotes
        /// </summary>
        [Required]

        [DataMember(Name="privateNotes")]
        public string PrivateNotes { get; set; }

        /// <summary>
        /// Gets or Sets SharedNotes
        /// </summary>

        [DataMember(Name="sharedNotes")]
        public string SharedNotes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class IdNotesBody {\n");
            sb.Append("  ClientId: ").Append(ClientId).Append("\n");
            sb.Append("  PrivateNotes: ").Append(PrivateNotes).Append("\n");
            sb.Append("  SharedNotes: ").Append(SharedNotes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((IdNotesBody)obj);
        }

        /// <summary>
        /// Returns true if IdNotesBody instances are equal
        /// </summary>
        /// <param name="other">Instance of IdNotesBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IdNotesBody other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ClientId == other.ClientId ||
                    ClientId != null &&
                    ClientId.Equals(other.ClientId)
                ) && 
                (
                    PrivateNotes == other.PrivateNotes ||
                    PrivateNotes != null &&
                    PrivateNotes.Equals(other.PrivateNotes)
                ) && 
                (
                    SharedNotes == other.SharedNotes ||
                    SharedNotes != null &&
                    SharedNotes.Equals(other.SharedNotes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ClientId != null)
                    hashCode = hashCode * 59 + ClientId.GetHashCode();
                    if (PrivateNotes != null)
                    hashCode = hashCode * 59 + PrivateNotes.GetHashCode();
                    if (SharedNotes != null)
                    hashCode = hashCode * 59 + SharedNotes.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(IdNotesBody left, IdNotesBody right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(IdNotesBody left, IdNotesBody right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
